### ISSUE TITLE
Can renderedMessage be used as the TraceTelemetry message?

### ISSUE THREAD

**Issue by JSkimming** [serilog/serilog-sinks-applicationinsights#11]
Hi

We've just started using this library, and we're very happy with is so far, I do you a have question/change request.

We're writing to trace (I see it's a [recent addition](https://github.com/serilog/serilog-sinks-applicationinsights/commit/0677fca65ff23123a667827660756bb646c6cc86)) and I was initially confused to find the message template as the trace message.

I assume it's [by design with Events](https://github.com/serilog/serilog-sinks-applicationinsights/pull/3), but I was wondering if using the rendered message for trace would be the better option.

I'd be happy to submit a pull request if you agree, [looking at the code](https://github.com/serilog/serilog-sinks-applicationinsights/blob/d328e102bd3be5462b835bf0183e67a0adb7062c/src/Serilog.Sinks.ApplicationInsights/Sinks/ApplicationInsights/ApplicationInsightsTracesSink.cs#L50) I doubt it would be much work.

To give you an idea of why I think it's needed, here's what the trace messages look like in Azure.

![telemetrytrace](https://cloud.githubusercontent.com/assets/647706/15864709/12c37796-2cd0-11e6-8426-86ca264b2dd1.png)

**Comment by jbattermann** [comment]
Good evening James,

yep - I certainly agree that for Traces the rendered message would make much more sense. However there's a similiar problem with Trace telemetries as there is/was with Events: the [message content is limited to 10kb](https://github.com/Azure/azure-content/blob/master/articles/application-insights/app-insights-export-data-model.md#trace-messages). So while I am still not entirely happy with the way Events are handled (because that PR #3 didn't actually 'fix' that a mere 250chars limit) I wouldn't change the Event Sink at the moment but certainly would do it for Traces.

Application Insights drops / used to drop telemetries that went beyond those restrictions completely so I am going a bit back and forth what to do - throw an ArgumentException if the renderedMessage   is bigger than 10k or adding more logic that splits up the single logEvent into multiple AI Traces at sizes of 10k-1 each.

Throwing an ArgumentException might not be the best choice (assuming the worst case here that during development only smaller trace messages, therefore no-one might handle the ArgumentException in their code and then, one day in production in the middle of the night a random trace > 10k occurs and the application crashes).

What would you think / expect as a Sink user?

**Comment by ndrochak** [comment]
For me, truncating the message seems like a reasonable approach. Agreed that throwing exceptions from your logger is not exactly the most friendly thing to do.

**Comment by jbattermann** [comment]
Yeah good point @ndrochak :+1: I would / will update the parameter documentation explaining the 10k limit so devs know what's going on and why and can handle larger messages themselves if applicable.

Sounds good @JSkimming ?

**Comment by JSkimming** [comment]
Hi Jörg, Nick

Thanks both for replying.

I agree with Nick about the exceptions, logging should be very forgiving, and not throw exceptions, does Serilog provide a method for accessing internal errors?

As for the truncating or just leaving it to AI to drop the message. I'm not sure how/where you would choose to truncate, it may not be the rendered message, but a property that blows out the 10K limit. So I think you should just leave it to AI.

My personal opinion is, if someone is attempting to log in excess of 10K of data to AI, then they're doing it wrong. It is the wrong tool for their needs. I try to set-up several logging destinations, sinks in Serilog parlance (I'm new to Serilog BTW), and if I ever want to log such large about of data, I do it a different way, e.g. to a file, table or blob storage.

Does the PR #12 I raised work for you, are there any changes/additions you'd like. I can't do any more work this evening, my wife and I are watching [GOT](https://en.wikipedia.org/wiki/Game_of_Thrones) :european_castle: :smile:

**Comment by wimagee** [comment]
I've just been trying the serilog / app insight integration this evening - it's worked perfectly for me apart from this issue. Having the rendered message come through as the trace message would make me very happy! :) And I really don't care whether it drops or truncates message over 10k - rather it didn't throw an exception though.

**Comment by jbattermann** [comment]
I've merged @JSkimming's PR #12 in as it is / was for now because this issue right here and #12 are about using the rendered message rather than the template and that was fixed in his PR :!

The topic regarding how to handle messages > 10k is better left in a separate issue. I'll give it a try over the weekend (I am a bit busy this week) and check how AI actually behaves for messages > 10k these days.

Thanks everyone and enjoy GOT @JSkimming ! 😄

**Comment by JSkimming** [comment]
:+1: :shipit:
