### ISSUE TITLE
Implement destructuring for structures

### ISSUE THREAD

**Issue by olegKoshmeliuk** [serilog/serilog-sinks-applicationinsights#13]
Hi,
Recently i have started to using AI sinks, and mentioned few issues:
1. **"** and **\** was escaped with \ (this is broking json text fields)
2. Any string is wrapped by **"**
2. Object destructuring was broken
3. AI analytics threat custom dimetions as strings only. 
I propose fix for writing scalar value properties, and somekind of destructuring for application insights
for example

``` c#
logger.Information("Got request:{@string} and {@dto} ", "[\"string\"]",
                new
                {
                    number = 1,
                    list = new object[] {1, "test"},
                    inner = new {a = "a", b = "b"},
                });
```

Will produce this properties:
Old:

``` json
{
  "LogLevel": "Information",
  "RenderedMessage": "Got request:\"[\\\"string\\\"]\" and { number: 1, list: [1, \"test\"], inner: { a: \"a\", b: \"b\" } }",
  "string": "\"[\\\"string\\\"]\"",
  "dto": "{ number: 1, list: [1, \"test\"], inner: { a: \"a\", b: \"b\" } }"
}
```

I proposing new implementation:

``` json
{
  "LogLevel": "Information",
  "MessageTemplate": "Got request:{@string} and {@dto}",
  "RenderedMessage": "Got request:\"[\\\"string\\\"]\" and { number: 1, list: [1, \"test\"], inner: { a: \"a\", b: \"b\" } }",
  "string": "[\"string\"]",
  "dto.number": "1",
  "dto.list.0": "1",
  "dto.list.1": "test",
  "dto.list.Count": "2",
  "dto.inner.a": "a",
  "dto.inner.b": "b"
}
```

I already implemented this features and ready to make pull request.

**Comment by jbattermann** [comment]
Hi Oleg,

thanks for the issue and yeah, Properties are currently treated quite simplistic. If you [check how other sinks are handling them](https://github.com/search?p=1&q=org%3Aserilog+logevent.properties&type=Code) there's a variety of different solutions (depending on the logging target), but many that only support a flat, simple structure use a static 'simplification' formatter such as the [Azure DocumentDB](https://github.com/serilog/serilog-sinks-azuredocumentdb/blob/master/src/Serilog.Sinks.AzureDocumentDb/Sinks/AzureDocumentDb/DocumentDbPropertyFormatter.cs), [SignalR](https://github.com/serilog/serilog-sinks-signalr/blob/master/src/Serilog.Sinks.SignalR/Sinks/SignalR/SignalRPropertyFormatter.cs), [RayGun](https://github.com/serilog/serilog-sinks-raygun/blob/master/src/Serilog.Sinks.Raygun/Sinks/Raygun/RaygunPropertyFormatter.cs), ...

So while your code looks good from an implementation point of view (just took a quick glimpse), from a maintainability point of view I lean towards pulling in what the other sinks are using and therefore keep this sink aligned with the others.

Would that approach be feasible / satisfactory for you, too?

**Comment by nblumhardt** [comment]
Hi @olegKoshmeliuk and @jbattermann;

I'm not sure if the simplifier from the other sinks will help - it still ends up creating structured JSON, which will be pretty close to what's happening here already. IIRC the simplifier is needed because the serializers provided by Azure DocumentDB and friends can only operate on native types like `Dictionary<K,V>` rather than Serilog's ones.

As luck would have it, I've just opened a PR on the Serilog repository that has some building blocks that could help here. These kinds of problems - manipulating `LogEventPropertyValue` into various formats - are common to a lot of sinks so we will ideally make improvements to that situation in Serilog 2.

The PR is: https://github.com/serilog/serilog/pull/772

There are two things that should help.

1. The `"\"[\\\"string\\\"]\""` problem. The PR includes a new type `JsonValueFormatter` that can turn any property value into JSON. Just running `JsonValueFormatter.Format()` over the scalar value should fix this. It looks like the sink is currently going from string -> Serilog's default display formatting -> JSON, which is a bit hard on the eyes :).

2. (I assume your fix @olegKoshmeliuk will do something similar...) The `LogEventPropertyValueVisitor` type implements the traversal across the property data, including a `state` argument to collect `dto.list.Count` path information.

I don't know if the Serilog functionality will be ready in time to be beneficial here, but perhaps we could look at taking the changes (which would fix some major usability pain points) with the plan to move across to the shared implementation when that lands? I could help pick up the consolidation work if so :)

**Comment by olegKoshmeliuk** [comment]
At start i was fixing the string properties  escaping, latter i was inspired by implementation of [JsonFormatter.cs](https://github.com/serilog/serilog/blob/dev/src/Serilog/Formatting/Json/JsonFormatter.cs) for producing json for complex objects and decided to fix complex objects too :smile:.
From other side AI support only attaching Dictionary<string,string> as custom dimensions. so in my fork i implemented flattering for complex objects instead of serializing them into json, i think flattering can be optional feature in sink so client can select flatter/serialize/both complex objects.

I Think that flattering is a good feature to have in case AI.
For example we can write such AI analytics requests:
With flattering:
`customEvents | where customDimensions.dto.list.Count > 1 | summarize count() by client_IP`
Wihout flattering(customDimensions.dto contain fixed json): 
`customEvents | extend dto=parsejson(customDimensions.dto) | where  dto.list.Count> 1 | summarize count() by client_IP`

**Comment by olegKoshmeliuk** [comment]
@jbattermann It's fine for me to rewrite PR latter with reusing common implementation for unwrapping  serilog classes into nested Dictionary<string, object> i can reuse that code in my PR and latter translate into flat Dictionary<string, string>.

@nblumhardt  `JsonValueFormatter.Format()` can be used for complex objects json, but for strings AI expect actual value in customDimensions argument(Dictionary<string, string>) and not the json encoded string.

**Comment by olegKoshmeliuk** [comment]
I will move flattering to new class `Dictionary<string,string> ApplicationInsightsPropertyFormatter.Simplify(IEnumerable<LogEventPropertyValue> prop)` and make a pull request.
@jbattermann would that PR be satisfactory quality for you?

**Comment by jbattermann** [comment]
@olegKoshmeliuk absolutely, yeah - thanks!
