### ISSUE TITLE
TelemetryClient assigned to Serilog not get passed when creating a contextual  logger for class

### ISSUE THREAD

**Issue by ExceptionCaught** [serilog/serilog-sinks-applicationinsights#22]
Currently, we are using Serilog together with ApplicationInsights to log the system. One issue we try to solve is attach a unique operation ID to the every log message in a single request. So an error message can be traced.

When build the ILogger for the container

`serilogConfig.WriteTo.ApplicationInsightsTraces(telemetryClient);
`
The telemtryClient is registerd as instancePerRequest and assigned with a unique OperationID in one of the actionAttribute on the Controller

```
public override void OnActionExecuting(HttpActionContext actionContext)
{
    var requestScope = actionContext.Request.GetDependencyScope();
    var telemetryClient = requestScope.GetService(typeof(TelemetryClient)) as TelemetryClient;
    telemetryClient.Context.Operation.Id = Guid.NewGuid().ToString();
    base.OnActionExecuting(actionContext);
}
```
And inside the constructor of a controller requires logging

```
public ControllerA(ILogger logger)
{
    var contextLogger = logger.ForContext<ControllerA>();
}
```
Now the problem is that the operationID does not appear on the log message. 

Even if we register the main ILogger as instancePerRequest, will the contextLogger still getting the same dependency object as the main one?

Additional comments:
If we were able to set the operationID on the TelemetryClient, ( which is supposed to be singleton). But this is not thread safe. One we request set operatinID and start logging, but in between, the another web request kicks in and reset this operationID.
Initially, we register TelemetryClient as singleton, but this operationID stay the same for each request, and it is also recommended to created telemtryClient instance per request
https://social.msdn.microsoft.com/Forums/en-US/fefbea33-2f0c-4cb0-9864-25cf9f1991d2/is-telemetryclient-threadsafe?forum=ApplicationInsights

We are using versin 2.1.0. Thanks

**Comment by jbattermann** [comment]
Hi @JonathonWei as far as I understand you are creating new logger instances per request & the problem is that by default the Serilog AI sink uses a singleton telemetry client?

You can solve this with the current version of the serilog sink by creating a custom Telemetry Client per Request yourself (and set the Operation ID you mentioned) and pass that instance into the serilog instance (also created per request) as shown i.e. in the  [Readme.md](https://github.com/serilog/serilog-sinks-applicationinsights#or-where-did-my-messages-go).


The Sink itself doesn't know / care about the usage - whether it is a along-running service application or a web app that might require per-request instances.. but you can do it either way.


Does this help/solve your problem?

**Comment by JonathonWei** [comment]
Hi @jbattermann , is there any possibility that ILogger will registered as singleton? I understand that int normal scenario the singleton should not depend on instancePerRequest.
However, from my understand and on the documentation, the ILogger.ForContext<>() will create a new contextual logger for the current web request already. This is already instance Per Request.
Is there anyway that even the ILogger is registered as singleton, the contextual logger will get the telemetryClient created in the attribute.OnActionExecuting()?

**Comment by JonathonWei** [comment]
Additionally, the LoggerConfiguration only allow to createLogger() once.
If the Ilogger is registered instancePerRequest, then this LoggerConfiguration also needs to be instancePerRequest?
