### ISSUE TITLE
Log message with exception gets recorded as Server Exception rather than a trace

### ISSUE THREAD

**Issue by robdmoore** [serilog/serilog-sinks-applicationinsights#27]
Hi,

I've noticed an interesting behaviour where any log event that has an exception attached to it gets registered in App Insights as a server exception rather than a trace message. This means that when viewing the data in the Azure Portal you loose the log message unless you dig into the properties of the exception.

I wonder if there should be a way to tell this sink to split it into a trace/event and then the exception as a separate thing?

**Comment by jbattermann** [comment]
Evening Rob,

yep, that's the behaviour as described in the [Readme](https://github.com/serilog/serilog-sinks-applicationinsights/blob/master/README.md) (first third) and you can customize how log messages are sent over to AI by using the overload described there, too:

```
var log = new LoggerConfiguration()
    .WriteTo
	.ApplicationInsights("<MyApplicationInsightsInstrumentationKey>", LogEventsToMetricTelemetryConverter)
    .CreateLogger();

// ....

private static ITelemetry LogEventsToMetricTelemetryConverter(LogEvent serilogLogEvent, IFormatProvider formatProvider)
{
    var metricTelemetry = new MetricTelemetry(/* ...*/);
    // forward properties from logEvent or ignore them altogether...
    return metricTelemetry;
}
```
..well rather than returning a MetricTelemetry as mentioned in the example up there, you can check what/how ITelemetry instances are built using the [default implementation(s)](https://github.com/serilog/serilog-sinks-applicationinsights/tree/master/src/Serilog.Sinks.ApplicationInsights/Sinks/ApplicationInsights).

That way you can change the behaviour how Exceptions are logged quite easily yourself.

Hope that helps!

Cheers,
-Jörg

**Comment by robdmoore** [comment]
Thanks for getting back to me @jbattermann :)

That makes sense. One question though: if I wanted to log two bits of telemetry from the same data (an exception and a trace) is that possible?

I guess I could just keep a reference to the `TelemetryClient` and in that method call it for one bit of telemetry and return the other bit of telemetry?

**Comment by jbattermann** [comment]
Sure thing and yeah you 'could' do that, but that would be a little bit low-level. I think I can easily add an overload TelemetryBuilder <Func... > that would return an IList<ITelemetry> and the serilog sink would send those over to AI...

Yeah.. I think that makes sense... I'll add it a bit later today, push a new NuGet package and let you know...

Cheers,
-J

**Comment by robdmoore** [comment]
That would be amazing :)

**Comment by aloneguid** [comment]
added this functionality to v2.6.2, please reopen if any issues
