### ISSUE TITLE
Move to the latest .csproj format

### ISSUE THREAD

**Issue by cmatskas** [serilog/serilog-sinks-applicationinsights#29]
Hi @jbattermann any thoughts of moving the project to the latest `.csproj` format? I've noticed that the main Serilog branch has already moved. Any reason why this one is still using the `project.json` format?
I'll be happy to send you a PR if you're sort of time. Let me know if I can help

**Comment by jbattermann** [comment]
Good evening @cmatskas, the reason why it's still on the 'intermediary' project.json format is indeed my lack of time lately but if you do send over a PR, I'll gladly merge it in!

Maybe take a glance at / inspiration from the other sinks that already did the move over to the new .csproj format in regards to the Build.ps1 / appveyor.yml files they have.. there might also have been some changes in those since the switch to project.json for this sink right here.

Cheers and thanks!

**Comment by nblumhardt** [comment]
To make this work smoothly (particularly so that we can publish and test pre-release packages from the repository), I think it'd make sense to create a `dev` branch in this repository and target the PR there.

Other Serilog sinks already include logic in the build/appveyor scripts to detect dev vs. master, and generate pre-release packages when built from dev.

If this sounds like the way to go, I can help set it up.

**Comment by cmatskas** [comment]
Ha, I didn't realise you only had a **master** branch until you mentioned it here. I'll create a **dev** branch and then I'm more than happy to create my own branch to merge into `dev`. Thoughts?

**Comment by jbattermann** [comment]
Sounds good & 'dev' branch is created 👍

**Comment by cmatskas** [comment]
@jbattermann do you have an example sink that I could follow to add the custom logic for build/appveyor scripts?

**Comment by nblumhardt** [comment]
@cmatskas this one should be current: https://github.com/serilog/serilog-sinks-console

**Comment by aloneguid** [comment]
closing as it's merged
