### ISSUE TITLE
NuGet .NET Standard v1.6 package requires full AspNetCore instead of just Microsoft.ApplicationInsights?

### ISSUE THREAD

**Issue by Tawnos** [serilog/serilog-sinks-applicationinsights#33]
Is there a significant change between .NET Standard v1.3 and v1.6 that it takes a dependency on  Microsoft.ApplicationInsights.AspNetCore and thus requires the full set of ASP.net packages instead of adding a v1.3 dependency to the Microsoft.ApplicationInsights package?

**Comment by timhermann** [comment]
I submitted a PR: https://github.com/serilog/serilog-sinks-applicationinsights/pull/34

**Comment by rsnj** [comment]
Is this repository still active? Merging this PR would be really helpful.

**Comment by jbattermann** [comment]
@Tawnos / @timhermann / @rsnj thanks for your inquiries / findings / PR.. and sorry it takes / took so long - this repository / project is not really maintained by me anymore (job/life etc) but I just merged in another / older PR #31 and it (among other things) also contains a similar fix / change regarding .Net Standard v1.3 (non .AspNetCore dependency) and .Net Standard v1.6 (as it was.. pulling in the .AspNetCore package).

So I think this solves this issue here, too.. and it'll be merged into the master branch and a build/package should be up once that's done (see #36).

**Comment by rsnj** [comment]
@jbattermann no worries thanks for the quick reply. We really enjoy Serilog, so thanks for all the hard work. Any idea on when you can push up a new package release to Nuget with this change?

**Comment by jbattermann** [comment]
Closed by #41 !
