### ISSUE TITLE
AI events do not show in AI site

### ISSUE THREAD

**Issue by hgjura** [serilog/serilog-sinks-applicationinsights#6]
Hello, I am using this library with all the defaults (I am only setting the Instrument Key). When tests that run to try to test this generate the following in the Output window: Application Insights Telemetry: {"name":"Microsoft.ApplicationInsights.< my key >.Event","time":"2016-03-06T16:24:59.9692781-05:00","iKey":"<my key>","tags":{"ai.internal.sdkVersion":"1.2.3.490"},"data":{"baseType":"EventData","baseData":{"ver":2,"name":"Right: {somedata} Left: {Left}","properties":{"LogLevel":"Information","RenderedMessage":"Right: \"{ Left = 100, Right = 500, Top = 504, Bottom = 143 }\" Left: 100","somedata":"\"{ Left = 100, Right = 500, Top = 504, Bottom = 143 }\"","Left":"100"}}}}

However none of the messages do show on the AI portal.

If I create an event using AI libraries (and use Flush()) the test events show in the portal.

Thanks
Herald

**Comment by jbattermann** [comment]
Good evening Herald,

by "_tests that run_" you mean i.e. Unit tests with a 'limited' process lifespan? If so it is expected and actually default AI behaviour - the messages are obviously not sent to AI synchronously but whenever the MS API actually "deems necessary" (typically in regular interval, whenever an internal queue reaches a threshold limit and then typically in bulk).

I don't have the direct link to the documentation on hand (but i.e. the "Developer mode" sends immediately, see https://azure.microsoft.com/en-us/documentation/articles/app-insights-configuration-with-applicationinsights-config/) but that's also why your forced .Flush() seems to 'work' - you just force the MS API to send the queued messages right away instead of whenever the API seems fit.

This is an AI feature and not really an 'issue' with this sink, so you can check whether either of the two Sink hooks (https://github.com/serilog/serilog-sinks-applicationinsights/blob/master/src/Serilog.Sinks.ApplicationInsights/LoggerConfigurationApplicationInsightsExtensions.cs#L91 and https://github.com/serilog/serilog-sinks-applicationinsights/blob/master/src/Serilog.Sinks.ApplicationInsights/LoggerConfigurationApplicationInsightsExtensions.cs#L68) allow you to either change that queue/timeout behaviour or force Developer mode for your tests even when run in i.e. Release mode.

Hope that helps a little,
-J
