### ISSUE TITLE
FileNotFoundException: Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.4.0.0'

### ISSUE THREAD

**Issue by alanafrankly** [serilog/serilog-sinks-applicationinsights#80]
I'm getting the following error when implementing WriteTo.ApplicationInsightsEvents()

`System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.'`

I have the following versions:

Serilog: 2.6.0
Microsoft.ApplicationInsights: 2.8.1
Serilog.Sinks.ApplicationInsights: 2.6.0

Not sure what's going on here, as this originally worked for me.

**Comment by jbattermann** [comment]
Seems like you're missing binding redirects for the Microsoft.ApplicationInsights assembly in your app.config .. the AI serilog sink was built against version 2.4.0.0 of the Microsoft.ApplicationInsights assembly, I however assume you updated the Microsoft.ApplicationInsights (NuGet) package to 2.8.1 and therefore the versions do no longer match. Without binding redirects the .Net runtime indicates (via the exception) that it correctly expects and misses exactly that - a version 2.4.0.0.

So if you're sure 2.8.1 of the MS AI package works as a replacement for 2.4.0.0 one, you can / should configure the binding redirects as explained at https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions .

**Comment by alanafrankly** [comment]
It sounds like Serilog.Sinks.ApplicationInsights requires Microsoft.ApplicationInsights 2.4.0.0? The Nuget dictates that it requires > 2.5.1, so I figured updating was the right thing to do?

**Comment by jbattermann** [comment]
Nuget package version != Assembly version but I just checked (I don't remember all version infos and what's what from the top of my head.. been quite a while since I used this project myself) ... when installing the Serilog.Sinks.ApplicationInsights 2.6.0 package into a new project it pulls in in the expected 2.5.1 version of AI and that combo works.

What may however be is that your project/application already _does_ contain an now outdated binding redirect to v 2.4.0.0 .. I'd suggest checking your app.config whether it contains any such entries and remove/adapt them to the assembly version(s) your project now references.
