### ISSUE TITLE
Is this project alive? 🕸

### ISSUE THREAD

**Issue by aloneguid** [serilog/serilog-sinks-applicationinsights#85]
I'd like to contribute, having an experience in writing another logging framework. I have a lot of inside knowledge how AI works. From what I can see pull requests are hanging and some issues are very old. Would you consider looking at them or transferring ownership if you don't have time?

**Comment by jbattermann** [comment]
Good evening Ivan, I am/was the original author of this sink but as you have noticed, I haven't been maintaining it actively recently.. so I would highly appreciate handing _maintainership_ over... As for _ownership_ @nblumhardt maybe should/could chime in.. but I'd be happy to step back/out and hand maintenance/development and all that over - thanks for the offer! 👍

**Comment by nblumhardt** [comment]
Hey @jbattermann and @aloneguid ! Thanks for the offer of help, Ivan.

We've got a bit of a scheme going for managing maintainership in the @serilog org (managed through GitHub teams); I've added you as a maintainer of the repo @aloneguid, which should give you full permissions on the repo. (Welcome! :-D)

If you need a hand with anything while you find your way, feel free to @ mention me, I'm not able to "watch" all of the Serilog repositories because the flood of notifications is just too great :-) but I keep up with all the basics, CI, publishing and so-on, and can sort out anything that gets in the way 👍
